### ISSUE TITLE
I am getting a weird error when I run x-ray-phantom

### ISSUE THREAD

**Issue by winnemucca** [lapwinglabs/x-ray-phantom#11]
My first error is 
phantomjs-node: You don't have 'phantomjs' installed

My other error is 
Warning: phantomjs-2.0.0 already installed

I am running nodemon

Here is my package.json

"node-phantom-simple": "^2.0.1",
    "phantomjs": "^1.9.17",
    "x-ray": "^2.0.2",
    "x-ray-phantom": "^1.0.1"

**Comment by matthewmueller** [comment]
Oh you don't have phantom installed on your computer. I think you need to run `brew install phantomjs`

**Comment by matthewmueller** [comment]
Edit: sorry I misread. I don't think Nightmare supports Phantom 2.0.0 yet...

**Comment by winnemucca** [comment]
Oh, no worries.  I will look at changing phantom to an earlier version.  Is there one that works best?

**Comment by matthewmueller** [comment]
See if `1.9.7` works for you, that's the one I'm running

**Comment by winnemucca** [comment]
great thanks.

**Comment by misaxi** [comment]
I'm a bit confused - please shed some lights. Since this module depends on Nightmare, which in turn uses electron, why phantom is required?

**Comment by umpirsky** [comment]
@matthewmueller Why phantomjs is not `x-ray-phantom` dependency? And why do you encourage us to install it using brew when there is a npm package?

Also, I installer it with `npm install phantomjs --save` so I have it locally for my project, but still getting:

```
phantomjs-node: You don't have 'phantomjs' installed
```

Any help is appreciated. Thanks.
