### ISSUE TITLE
Sporadic Issue: PhantomJS has crashed

### ISSUE THREAD

**Issue by benmarten** [lapwinglabs/x-ray-phantom#14]
I am getting this sporadic issue...
Any ideas?

```
phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/07B6AB8A-E3C4-472A-9636-6686914FB06F.dmp

/Users/Ben/dev/chartScraper/node_modules/x-ray-phantom/node_modules/nightmare/lib/index.js:284
    throw err;
          ^
Error: the phantomjs process ended unexpectedly
    at Nightmare.handleCrash (/Users/Ben/dev/chartScraper/node_modules/x-ray-phantom/node_modules/nightmare/lib/index.js:281:15)
    at ChildProcess.<anonymous> (/Users/Ben/dev/chartScraper/node_modules/x-ray-phantom/node_modules/nightmare/node_modules/phantom/phantom.js:150:28)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

**Comment by stephengardner** [comment]
I'm having this issue on a simple scrape.  What was the source of your problem?  Did you fix this?

**Comment by benmarten** [comment]
No, i still run in this issue occasionally...

Which phantom version are you using? I am using 1.9.8, but I saw that there is phantom 2.x out there... maybe worth a shot?

**Comment by stephengardner** [comment]
I'm not new to xray but new to phantomjs so I downloaded the npm module and thought all would be well.

Turns out I needed the standalone module from the phantomjs website, installed, added the /bin folder to my PATH, and all worked well.  I'm using the latest (2.1.1) right now.  Although I haven't tested enough to know if this is a sporadic issue, at least it works for me now.

**Comment by benmarten** [comment]
Yeah I think i need to upgrade to 2.1.1 and see if the issue persists. thx for the feedback ;)

**Comment by stephengardner** [comment]
Likewise.  Cheers

**Comment by benmarten** [comment]
Works for me now, also with latest versions of xray and phantom ;)
