### ISSUE TITLE
Failing to pass options to nightmare

### ISSUE THREAD

**Issue by ghostfreak3000** [lapwinglabs/x-ray-phantom#18]
The Usage code snippet.

``` javascript
var phantom = require('x-ray-phantom');
var Xray = require('x-ray');

var x = Xray()
  .driver(phantom());

x('http://google.com', 'title')(function(err, str) {
  if (err) return done(err);
  assert.equal('Google', str);
  done();
})
```

produces this error.
![selection_003](https://cloud.githubusercontent.com/assets/5859565/13553139/30bbd090-e333-11e5-8fd5-f2ee95613efb.png)

Which is basically a XSS scripting security error. so naturally the solution is to disable web security in nightmare... with this code.

``` javascript
var phantom = require('x-ray-phantom');
var Xray = require('x-ray');

var phantom_opts = {
  webPreferences:{
    webSecurity:false
  }
}

var x = Xray()
  .driver(phantom(phantom_opts));

x('https://google.com', 'title')(function(err, str) {
  if (err) return done(err);
  assert.equal('Google', str);
  done();
})
```

Still produces the same error.
Got options structure from [here](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions)

PS:
The phantom process doesn't exit on this error.. not good. anyway we can set it to fail on error?

**Comment by stpch** [comment]
Try with just `var phantom_opts = {webSecurity: false};`. Works for me.

**Comment by ghostfreak3000** [comment]
It worked... though that means there's a slight difference between the documented options object and the actual one (WIll bite me in the ass when doing advanced crawling in the future)

Thanks alot!
